# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVwe5jHalQe57vHPwo4XLurZoIwfuYi0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/salary_data.csv")

df

#df.shape #How big is the data

#df.sample(10) # Choose random sample
#df.info() #Show data type of coloumn
#df.isnull().sum() #Find any missing value
#df.duplicated().sum() #Show duplicated value from table
#df.corr() #Find corelation
#df.corr()['Fare']

#age_min = df['Age'].mean()
#df["Age"].fillna(age_min, inplace = True)


#Extract columns from dataset
X = df[['YearsExperience']]
Y = df[['Salary']]


X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.30)

regressor = LinearRegression()
regressor.fit(X_train, Y_train)


# Visualizing the Training set results
plt.scatter(X_train, Y_train, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.title('Year of Experience VS Salary (Training set)')
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.show()


# Visualizing the Test set results
plt.scatter(X_test, Y_test, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.title('Year of Experience VS Salary (Test set)')
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.show()

'''



'''

"""# New Section"""

df.isnull().sum()

df

